version: '3.7'

services:
  db:
    image: postgres
    ports:
      - '9001:5432'
    volumes:
      - ./DB/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
      - ./DB/fill_tables.sql:/docker-entrypoint-initdb.d/fill_tables.sql
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=premadb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=supersecretpassword
    
  preenrollmentmgmt:
    build:
      context: ./premarum-backend
      dockerfile: Dockerfile.dev
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - DATABASE_SERVER_URL=postgresql://postgres:supersecretpassword@db:5432/premadb
    ports:
      - '8888:80'
    volumes:
      - ./premarum-backend/PreEnrollmentMgmt.WebApi/bin/Debug/net6.0:/app
    depends_on:
      - db

volumes:
  postgres_data: