version: '3.7'

services:
  db:
    image: postgres
    ports:
      - '9001:5432'
    volumes:
      - ./DB/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
      - ./DB/fill_tables.sql:/docker-entrypoint-initdb.d/fill_tables.sql
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=premadb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=supersecretpassword

volumes:
  postgres_data: