import * as React from 'react';
import type { AppProps } from 'next/app';
import { CacheProvider, EmotionCache } from '@emotion/react';
import { ThemeProvider, CssBaseline, createTheme } from '@mui/material';

import '@fontsource/roboto/300.css';
import '@fontsource/roboto/400.css';
import '@fontsource/roboto/500.css';
import '@fontsource/roboto/700.css';

import createEmotionCache from '../utility/createEmotionCache';
import lightThemeOptions from '../styles/theme/lightThemeOptions';
import Navbars from './components/navbars';
import Head from 'next/head';
import {Configuration, PublicClientApplication} from "@azure/msal-browser";
import {AuthenticatedTemplate, MsalProvider} from '@azure/msal-react';
import AuthDefaultLayout from './components/DefaultLayout'
import {NextPage} from "next";
import {ReactElement, ReactNode} from "react";

// MSAL configuration
const configuration: Configuration = {
  auth: {
    clientId: "83c3cbe7-f00e-4ea8-87d8-bf4d75690f17",
    authority: "https://login.microsoftonline.com/0dfa5dc0-036f-4615-99e4-94af822f2b84",
  }
};

export const pca = new PublicClientApplication(configuration);

const clientSideEmotionCache = createEmotionCache();

const lightTheme = createTheme(lightThemeOptions);

type NextPageWithLayout = NextPage & {
  getLayout?: (page: ReactElement) => ReactNode
}

type AppPropsWithLayout = AppProps & {
  Component: NextPageWithLayout,
  emotionCache?: EmotionCache;
}

const MyApp: React.FunctionComponent<AppPropsWithLayout> = (props) => {
  const { Component, emotionCache = clientSideEmotionCache, pageProps } = props;
  // Default Layout
  let DefaultLayout:  (page: ReactElement) => ReactNode = 
      ((page: ReactElement) =>
          (<AuthDefaultLayout>
              <Navbars>
                {page}
              </Navbars>
          </AuthDefaultLayout>)); 
  // Overloaded Layout defined on a per page basis
  if (Component.getLayout) {DefaultLayout = Component.getLayout;}
  return (
    <MsalProvider instance={pca}>
      <CacheProvider value={emotionCache}>
        <ThemeProvider theme={lightTheme}>
          <CssBaseline />
          <Head>
          <title>PREMARUM</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
          </Head>
          {DefaultLayout(<Component {...pageProps} />)}
        </ThemeProvider>
      </CacheProvider>
    </MsalProvider>
  );
};

export default MyApp;
