import * as React from 'react';
import type { AppProps } from 'next/app';
import { CacheProvider, EmotionCache } from '@emotion/react';
import { ThemeProvider, CssBaseline, createTheme } from '@mui/material';

import '@fontsource/roboto/300.css';
import '@fontsource/roboto/400.css';
import '@fontsource/roboto/500.css';
import '@fontsource/roboto/700.css';

import createEmotionCache from '../utility/createEmotionCache';
import lightThemeOptions from '../styles/theme/lightThemeOptions';
import Navbars from './components/navbars';
import Head from 'next/head';
import {Configuration, PublicClientApplication} from "@azure/msal-browser";
import {AuthenticatedTemplate, MsalProvider, UnauthenticatedTemplate } from '@azure/msal-react';
import LoginButton from "./components/LoginButton";
import Landing from './landing';
//import '../styles/globals.css';
interface MyAppProps extends AppProps {
  emotionCache?: EmotionCache;
}

// MSAL configuration
const configuration: Configuration = {
  auth: {
    clientId: "83c3cbe7-f00e-4ea8-87d8-bf4d75690f17",
    authority: "https://login.microsoftonline.com/0dfa5dc0-036f-4615-99e4-94af822f2b84",
  }
};

const pca = new PublicClientApplication(configuration);

const clientSideEmotionCache = createEmotionCache();

const lightTheme = createTheme(lightThemeOptions);

const MyApp: React.FunctionComponent<MyAppProps> = (props) => {
  const { Component, emotionCache = clientSideEmotionCache, pageProps } = props;

  return (
    <MsalProvider instance={pca}>
      <CacheProvider value={emotionCache}>
        <ThemeProvider theme={lightTheme}>
          <CssBaseline />
          <Head>
          <title>PREMARUM</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
          </Head>
          <AuthenticatedTemplate>
            <Navbars>
              <Component {...pageProps} />
            </Navbars>
          </AuthenticatedTemplate>
          <UnauthenticatedTemplate>
            <Landing />
          </UnauthenticatedTemplate>
        </ThemeProvider>
      </CacheProvider>
    </MsalProvider>
  );
};

export default MyApp;
