import { Grid, Typography } from '@mui/material'
import type { NextPage } from 'next'
import Head from 'next/head'
import Navbars from './components/navbars'

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>PremaRUM</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>



      <Grid container>
        <Navbars/>
      </Grid>
    </div>
  )
}

export default Home
