import { Grid, Typography } from '@mui/material'
import type { NextPage } from 'next'
import Head from 'next/head'

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>PremaRUM</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Grid container>
        <Grid item>
          <Typography>This is title page</Typography>
        </Grid>
      </Grid>

    </div>
  )
}

export default Home
